---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbook_path: ./test/cookbooks
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: nginx
    run_list:
      - 'recipe[nginx]'
      - 'recipe[ssl-config::nginx]'
    attributes:
  - name: apache
    run_list:
      - 'recipe[apache2]'
      - 'recipe[ssl-config::apache]'
    attributes:
