name             'ssl-config'
maintainer       'Jeremy Olliver'
maintainer_email 'jeremy.olliver@gmail.com'
license          'Apache 2.0'
description      'Generates secure TLS config file'
long_description 'Generates secure TLS config file for Apache/Nginx to the webserver root config at secure-ssl.conf'
version          '0.1.0'

recommends 'nginx'
recommends 'apache2'
